#!/usr/bin/env python

import argparse

from backend.scan import scan

parser = argparse.ArgumentParser(   prog="hackeraptor",
                                    description="All-in-one hacking tool" )
subparsers = parser.add_subparsers(help="main command")

subparser = subparsers.add_parser("scan", help="scan ports")
subparser.set_defaults(func=scan)
subparser.add_argument("host", help="host to scan")
subparser.add_argument("-t", "--tcp", help="scan tcp ports", required=False)
subparser.add_argument("-u", "--udp", help="scan udp ports", required=False)

args = parser.parse_args()
if "func" in args:
    args.func(args)
else:
    parser.print_help()
